### ISSUE TITLE
How to use the IdleHide.css

### ISSUE THREAD

**Issue by khoint0210** [ShiniGandhi/JellyTheme#1]
![CleanShot 2022-06-10 at 11 23 28](https://user-images.githubusercontent.com/12799726/172989995-5cbccd60-7420-4ea4-a0d2-36b8eff47ea6.png)
After format the  itemDetails-index-html. Which line I should put the js code to ?

May I have your  itemDetails-index-html file as an example
```
!function(n){"use strict";n.fn.idle=function(e){var t,i,o={idle:6e4,events:"mousemove keydown mousedown touchstart",onIdle:fun$
$(document).idle({
  onIdle: function(){
    document.body.classList.add("idle");
  },
 onActive: function(){
    document.body.classList.remove("idle");
 },
  idle: 20000
})
```

**Comment by Amarel-LTD** [comment]
You put it at the end of the file, I'll clarify that in the README.md as well

**Comment by khoint0210** [comment]
I put that add to the end of the file and it has the error
![CleanShot 2022-06-10 at 14 06 08](https://user-images.githubusercontent.com/12799726/173009776-bd009110-3d6d-4b6f-bf50-4db64dc9134d.png)

Here is the  itemDetails-index-html 
![CleanShot 2022-06-10 at 14 07 23](https://user-images.githubusercontent.com/12799726/173009922-55beac26-862c-4ebc-a98c-413e12ad2ec8.png)

**Comment by Amarel-LTD** [comment]
Oh fuck my bad, this isn't the full code, it didn't copy the entire text block for some reason. I've updated the file now.
Here's the full code:
```// IDLE DETECT //
!function(n){"use strict";n.fn.idle=function(e){var t,i,o={idle:6e4,events:"mousemove keydown mousedown touchstart",onIdle:function(){},onActive:function(){},onHide:function(){},onShow:function(){},keepTracking:!0,startAtIdle:!1,recurIdleCall:!1},c=e.startAtIdle||!1,d=!e.startAtIdle||!0,l=n.extend({},o,e),u=null;return n(this).on("idle:stop",{},function(){n(this).off(l.events),l.keepTracking=!1,t(u,l)}),t=function(n,e){return c&&(e.onActive.call(),c=!1),clearTimeout(n),e.keepTracking?i(e):void 0},i=function(n){var e,t=n.recurIdleCall?setInterval:setTimeout;return e=t(function(){c=!0,n.onIdle.call()},n.idle)},this.each(function(){u=i(l),n(this).on(l.events,function(){u=t(u,l)}),(l.onShow||l.onHide)&&n(document).on("visibilitychange webkitvisibilitychange mozvisibilitychange msvisibilitychange",function(){document.hidden||document.webkitHidden||document.mozHidden||document.msHidden?d&&(d=!1,l.onHide.call()):d||(d=!0,l.onShow.call())})})}}(jQuery);

$(document).idle({
  onIdle: function(){
    document.body.classList.add("idle");
  },
 onActive: function(){
    document.body.classList.remove("idle");
 },
  idle: 20000
})
```

**Comment by khoint0210** [comment]
after having the script it work but it look does not right 
<img width="864" alt="CleanShot 2022-06-10 at 14 47 28@2x" src="https://user-images.githubusercontent.com/12799726/173017237-6cf2903c-0649-439e-b60f-23dc8cb4d682.png">

**Comment by Amarel-LTD** [comment]
I figured out why this happens, I forgot that I've set up the genres to be above the description in the `itemDetails-index-html` file.
Pushed an update without a line that makes the track selection go way up.
