### ISSUE TITLE
NOT A ISSUE BUT A QUESTION 

### ISSUE THREAD

**Issue by tywentghxst** [ShiniGandhi/JellyTheme#3]
Sorry if this waste your time, I love your theme, and had a question on how you made the my media section on mobile go from big to small like that as well as removing the my media title above it? It looks sooooo good and I can't figure it out and am trying to add that specific line to my css to keep it there for any changes I make other theme swaps. Again sorry to bother you! 
![Screenshot_20220721-133638_Jellyfin](https://user-images.githubusercontent.com/77469443/180278799-1363e461-1cb2-4ed7-aa2a-1009d01e4b0b.jpg)
![Screenshot_20220721-141426_Jellyfin](https://user-images.githubusercontent.com/77469443/180278807-f1859a19-9181-4a0e-b494-a7bd6204fc8e.jpg)

**Comment by Amarel-LTD** [comment]
In the home settings, change `My Media` to `My Media (small)`
![image](https://user-images.githubusercontent.com/55044876/180512324-4d48ab1c-32de-4e89-b814-669c2116784f.png)
