### ISSUE TITLE
Backdrop not showing

### ISSUE THREAD

**Issue by sevi-kun** [ShiniGandhi/JellyTheme#5]
Hey, thank you for your great work.

On my instance the backdrop isn't showing up.. even tho the movie/show has a backdrop stored.

Any idea how I could fix that?

Thank you <3

**Comment by sevi-kun** [comment]
To clarify what I mean, this is a show's main page:
![image](https://user-images.githubusercontent.com/43034898/208742829-d50570c7-3a20-4431-9118-3d187ab1200d.png)

**Comment by Amarel-LTD** [comment]
Can you show me your custom CSS section?
I've purposefully added a two-three second delay to the backdrop because sometimes it doesn't switch backdrops fast enough from the main-menu backdrops.
Also, do you have backdrops enabled in your user settings? I *think* that my CSS requires that (forgive me, it has been a while since I've done that part).

**Comment by sevi-kun** [comment]
Aaahhh.. Yes.. I disabled it in my user settings.. Thank you so much for your fast reply :)
The 2-3 second delay is pretty sad actually. I will figgle arround with it a bit to see if I can tweak that ;)

**Comment by Amarel-LTD** [comment]
I have a theory as to how to fix that, hopefully I'll have time to find a proper solution to it.
Another reason I have it is because my video backdrop takes a second to start on slower connections, so that helps it look more seamless in my case.

**Comment by sevi-kun** [comment]
I have an idea to set the homepage backdrop to something neutral (Jellyfin / blueish default backdrop or something like that). That way it's also less weird if it takes some seconds to load.

**Comment by Amarel-LTD** [comment]
The way I have it set up now is that the backdrop is in `display: none;` and a black background is behind it. I think that if I used opacity instead it would speed things up, as I think that kinda screws up with the way it transitions between them.

**Comment by sevi-kun** [comment]
I'm sorry, I don't have much experience with CSS. Where do you do the transition? I thought it would simply be something based on this [mozilla - transition](https://developer.mozilla.org/en-US/docs/Web/CSS/transition), but I don't quite understand how it's done.

Seems like this is setting the backdrop? 

`.backdropContainer {
    display: block !important;
}`

 I also saw that jellyfin loads multiple backdrops and cycles through them (on the home page)..

When I get home, I will have a closer look at it..

Thank you so far. If you want we could open a new issue for this and work it out together.

**Comment by Amarel-LTD** [comment]
The transition is built into Jellyfin, I only added a transition delay:
```
.backdropImageFadeIn {
    animation-delay: 3s;
}
```
The backdrop is hidden in the main menu with this:
```
.withSectionTabs .backdropImage {
display: none !important;
}
```
Which is disabled when you enter any media.
And sure, we can do that. I use video backdrops exclusively, but it would be good to have a less janky fix for this.
