### ISSUE TITLE
Not a issue, I'm looking for the CSS to enlarge the card overlay when the mouse goes over it.

### ISSUE THREAD

**Issue by WTrash** [ShiniGandhi/JellyTheme#7]
I think it's in JellyTheme.css but I don't see which part I need to isolate to have this functionality. 

![image](https://user-images.githubusercontent.com/118386399/219882336-a6a7f92e-2239-48dd-a998-1dac44c14082.png)

**Comment by Amarel-LTD** [comment]
Yes, it's `JellyTheme.css`, the cleaner version has the borders marked.

This is the part that zooms in:
```
.homeLibraryButton:hover,.homeLibraryButton:focus,.card:hover,.card:focus {
-webkit-filter:none!important;
box-shadow:0 0 20px #000;
filter:none!important;
transform:scale(1.2)!important
}
```

**Comment by WTrash** [comment]
Thank you 
I can't seem to put together the parts that have to do with the edges and such, so it looks like the theme.

**Comment by ghost** [comment]
sorry for the delay, didn't see the message
the part that is responsible for the rounding is `--rounding`.
you can change it by adding this:
```css
:root {
--rounding:7px !important;
}
```
make sure you add the `!important`, otherwise it might not take priority over the value set in my code
